version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: siamtech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # RAG Service (updated to include PostgreSQL agent)
  rag-service:
    build:
      context: .
      dockerfile: Dockerfile.rag
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - KNOWLEDGE_BASE_ID=${KNOWLEDGE_BASE_ID}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=siamtech
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    depends_on:
      - postgres
    restart: unless-stopped
    
  # Open WebUI
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://rag-service:5000/v1
      - OPENAI_API_KEY=sk-1234
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - rag-service
    restart: unless-stopped

volumes:
  postgres_data:
  open-webui-data: