model_list:
  # Claude 3.7 Sonnet
  - model_name: claude-3-7-sonnet
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: ap-southeast-1
    model_info:
      description: "Claude 3.7 Sonnet via AWS Bedrock"
      max_tokens: 200000
      input_modalities: ["TEXT", "IMAGE"]
      output_modalities: ["TEXT"]
      response_streaming_supported: true

  # Claude 3 Haiku
  - model_name: claude-3-haiku
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0
      aws_region_name: ap-southeast-1
    model_info:
      description: "Claude 3 Haiku via AWS Bedrock"
      max_tokens: 200000

general_settings:
  master_key: sk-1234
  completion_model: claude-3-7-sonnet

# RAG Settings - Custom approach
rag_settings:
  knowledge_base_id: ${KNOWLEDGE_BASE_ID}
  bedrock_region: ap-southeast-1
  retrieval_config:
    numberOfResults: 10
    searchType: "SEMANTIC"
  
litellm_settings:
  drop_params: true
  set_verbose: true  # เปิดเพื่อ debug
  
router_settings:
  routing_strategy: simple-shuffle