default_tenant: company-a

tenants:
  company-a:
    name: "SiamTech Main Office"
    description: "สำนักงานใหญ่ กรุงเทพมหานคร"
    
    database:
      host: postgres-company-a
      port: 5432
      database: siamtech_company_a
      user: postgres
      password: password123
      pool_size: 10
      max_overflow: 20
    
    knowledge_base:
      id: KJGWQPHFSM
      prefix: company-a
      bucket: siamtech-kb-company-a
      region: ap-southeast-1
      search_type: SEMANTIC
      max_results: 10
    
    api_keys:
      bedrock: ${AWS_ACCESS_KEY_ID}
      bedrock_secret: ${AWS_SECRET_ACCESS_KEY}
      openai: ${OPENAI_API_KEY_COMPANY_A}
    
    settings:
      max_tokens: 1000
      temperature: 0.7
      allow_hybrid_search: true
      enable_postgres_agent: true
      enable_knowledge_base_agent: true
      default_agent_type: "auto"
      response_language: "th"
    
    webhooks:
      n8n_endpoint: "http://n8n:5678/webhook/company-a-chat"
      health_check: "http://n8n:5678/webhook/company-a-health"
    
    contact_info:
      email: "info@siamtech.co.th"
      phone: "02-123-4567"
      address: "กรุงเทพมหานคร"

  company-b:
    name: "SiamTech Regional Office"
    description: "สาขาภาคเหนือ เชียงใหม่"
    
    database:
      host: postgres-company-b
      port: 5432
      database: siamtech_company_b
      user: postgres
      password: password123
      pool_size: 5
      max_overflow: 10
    
    knowledge_base:
      id: KJGWQPHFSM
      prefix: company-b
      bucket: siamtech-kb-company-b
      region: ap-southeast-1
      search_type: SEMANTIC
      max_results: 10
    
    api_keys:
      bedrock: ${AWS_ACCESS_KEY_ID}
      bedrock_secret: ${AWS_SECRET_ACCESS_KEY}
      openai: ${OPENAI_API_KEY_COMPANY_B}
    
    settings:
      max_tokens: 800
      temperature: 0.7
      allow_hybrid_search: true
      enable_postgres_agent: true
      enable_knowledge_base_agent: true
      default_agent_type: "auto"
      response_language: "th"
    
    webhooks:
      n8n_endpoint: "http://n8n:5678/webhook/company-b-chat"
      health_check: "http://n8n:5678/webhook/company-b-health"
    
    contact_info:
      email: "regional@siamtech.co.th"
      phone: "053-123-456"
      address: "เชียงใหม่"

  company-c:
    name: "SiamTech International"
    description: "สำนักงานต่างประเทศ"
    
    database:
      host: postgres-company-c
      port: 5432
      database: siamtech_company_c
      user: postgres
      password: password123
      pool_size: 8
      max_overflow: 15
    
    knowledge_base:
      id: KJGWQPHFSM
      prefix: company-c
      bucket: siamtech-kb-company-c
      region: ap-southeast-1
      search_type: SEMANTIC
      max_results: 10
    
    api_keys:
      bedrock: ${AWS_ACCESS_KEY_ID}
      bedrock_secret: ${AWS_SECRET_ACCESS_KEY}
      openai: ${OPENAI_API_KEY_COMPANY_C}
    
    settings:
      max_tokens: 1200
      temperature: 0.6
      allow_hybrid_search: true
      enable_postgres_agent: true
      enable_knowledge_base_agent: true
      default_agent_type: "auto"
      response_language: "en"  # English for international
    
    webhooks:
      n8n_endpoint: "http://n8n:5678/webhook/company-c-chat"
      health_check: "http://n8n:5678/webhook/company-c-health"
    
    contact_info:
      email: "international@siamtech.co.th"
      phone: "+66-2-123-4567"
      address: "Bangkok, Thailand"

# Global Settings
global_settings:
  # AWS Configuration
  aws:
    region: ap-southeast-1
    bedrock_model: "apac.anthropic.claude-3-7-sonnet-20250219-v1:0"
  
  # Security
  security:
    require_tenant_header: true
    default_tenant_on_missing: true
    tenant_header_name: "X-Tenant-ID"
    api_key_header_name: "X-API-Key"
  
  # Logging
  logging:
    level: INFO
    include_tenant_id: true
    log_queries: true
    log_responses: false  # Don't log full responses for privacy
  
  # Rate Limiting (per tenant)
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_limit: 10
  
  # Monitoring
  monitoring:
    enable_metrics: true
    metrics_endpoint: "/metrics"
    health_check_interval: 60  # seconds
  
  # Cache Settings
  cache:
    enabled: true
    ttl: 300  # 5 minutes
    redis_url: "redis://redis:6379"
    key_prefix: "siamtech_cache"

# Feature Flags
feature_flags:
  enable_hybrid_search: true
  enable_streaming_responses: false
  enable_conversation_history: true
  enable_analytics: true
  enable_auto_scaling: false

# Development Settings
development:
  debug_mode: false
  mock_database: false
  mock_knowledge_base: false
  enable_test_endpoints: true
  cors_origins: ["*"]

# Production Settings
production:
  debug_mode: false
  mock_database: false
  mock_knowledge_base: false
  enable_test_endpoints: false
  cors_origins: ["https://chat.siamtech.co.th"]
  ssl_required: true
  
# Backup Settings
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  backup_location: "s3://siamtech-backups/"

# Alerting
alerting:
  enabled: true
  channels:
    - type: email
      recipients: ["admin@siamtech.co.th"]
    - type: slack
      webhook_url: ${SLACK_WEBHOOK_URL}
  
  conditions:
    - name: "High Error Rate"
      metric: "error_rate"
      threshold: 0.1  # 10%
      duration: 300   # 5 minutes
    
    - name: "Database Connection Failed"
      metric: "database_connection_failed"
      threshold: 1
      duration: 60
    
    - name: "Knowledge Base Unavailable"
      metric: "knowledge_base_unavailable"
      threshold: 1
      duration: 60