default_tenant: company-a

tenants:
  company-a:
    name: "SiamTech Main Office"
    description: "สำนักงานใหญ่ กรุงเทพมหานคร"
    
    database:
      host: postgres-company-a
      port: 5432
      database: siamtech_company_a
      user: postgres
      password: password123
    
    knowledge_base:
      id: KJGWQPHFSM
      prefix: company-a
      bucket: siamtech-kb-company-a
      region: ap-southeast-1
      search_type: SEMANTIC
      max_results: 10
    
    api_keys:
      bedrock: ${AWS_ACCESS_KEY_ID}
      bedrock_secret: ${AWS_SECRET_ACCESS_KEY}
      openai: ${OPENAI_API_KEY_COMPANY_A}
    
    settings:
      max_tokens: 10
      temperature: 0.7
      allow_hybrid_search: true
      enable_postgres_agent: true
      enable_knowledge_base_agent: false
      default_agent_type: "postgres"
      response_language: "th"
    
    webhooks:
      n8n_endpoint: "http://n8n:5678/webhook/company-a-chat"
      health_check: "http://n8n:5678/webhook/company-a-health"
    
    contact_info:
      email: "info@siamtech.co.th"
      phone: "02-123-4567"
      address: "กรุงเทพมหานคร"

  company-b:
    name: "SiamTech Regional Office"
    description: "สาขาภาคเหนือ เชียงใหม่"
    
    database:
      host: postgres-company-b
      port: 5432
      database: siamtech_company_b
      user: postgres
      password: password123
    
    knowledge_base:
      id: KJGWQPHFSM
      prefix: company-b
      bucket: siamtech-kb-company-b
      region: ap-southeast-1
      search_type: SEMANTIC
      max_results: 10
    
    api_keys:
      bedrock: ${AWS_ACCESS_KEY_ID}
      bedrock_secret: ${AWS_SECRET_ACCESS_KEY}
      openai: ${OPENAI_API_KEY_COMPANY_B}
    
    settings:
      max_tokens: 80
      temperature: 0.7
      allow_hybrid_search: true
      enable_postgres_agent: true
      enable_knowledge_base_agent: false
      default_agent_type: "postgres"
      response_language: "th"
    
    webhooks:
      n8n_endpoint: "http://n8n:5678/webhook/company-b-chat"
      health_check: "http://n8n:5678/webhook/company-b-health"
    
    contact_info:
      email: "regional@siamtech.co.th"
      phone: "053-123-456"
      address: "เชียงใหม่"

  company-c:
    name: "SiamTech International"
    description: "สำนักงานต่างประเทศ"
    
    database:
      host: postgres-company-c
      port: 5432
      database: siamtech_company_c
      user: postgres
      password: password123
    
    knowledge_base:
      id: KJGWQPHFSM
      prefix: company-c
      bucket: siamtech-kb-company-c
      region: ap-southeast-1
      search_type: SEMANTIC
      max_results: 10
    
    api_keys:
      bedrock: ${AWS_ACCESS_KEY_ID}
      bedrock_secret: ${AWS_SECRET_ACCESS_KEY}
      openai: ${OPENAI_API_KEY_COMPANY_C}
    
    settings:
      max_tokens: 120
      temperature: 0.6
      allow_hybrid_search: true
      enable_postgres_agent: true
      enable_knowledge_base_agent: false
      default_agent_type: "postgres"
      response_language: "en"
    
    webhooks:
      n8n_endpoint: "http://n8n:5678/webhook/company-c-chat"
      health_check: "http://n8n:5678/webhook/company-c-health"
    
    contact_info:
      email: "international@siamtech.co.th"
      phone: "+66-2-123-4567"
      address: "Bangkok, Thailand"

# Global Settings  
global_settings:
  aws:
    region: ap-southeast-1
    bedrock_model: "apac.anthropic.claude-3-7-sonnet-20250219-v1:0"
  
  security:
    require_tenant_header: false
    default_tenant_on_missing: true
    tenant_header_name: "X-Tenant-ID"
  
  logging:
    level: INFO
    include_tenant_id: true
    log_queries: true
    log_responses: false

feature_flags:
  enable_hybrid_search: true
  enable_streaming_responses: false
  enable_conversation_history: true