default_tenant: company-a

tenants:
  company-a:
    name: "SiamTech Main Office"
    description: "สำนักงานใหญ่ กรุงเทพมหานคร"
    
    # FIXED: Remove pool_size and max_overflow (not supported by psycopg2)
    database:
      host: postgres-company-a
      port: 5432
      database: siamtech_company_a
      user: postgres
      password: password123
    
    knowledge_base:
      id: "dummy_kb_test_id"
      prefix: "company-a"
      bucket: "siamtech-kb-company-a" 
      region: "ap-southeast-1"
      search_type: "SEMANTIC"
      max_results: 10
    
    api_keys:
      bedrock: "dummy_test_key_12345"
      bedrock_secret: "dummy_test_secret_67890"
    
    settings:
      max_tokens: 1000
      temperature: 0.7
      allow_hybrid_search: true
      enable_postgres_agent: true
      enable_knowledge_base_agent: false
      enable_ollama_agent: true
      default_agent_type: "auto"
      response_language: "th"
    
    webhooks:
      n8n_endpoint: "http://n8n:5678/webhook/company-a-chat"
      health_check: "http://n8n:5678/webhook/company-a-health"
    
    contact_info:
      email: "info@siamtech.co.th"
      phone: "02-123-4567"
      address: "กรุงเทพมหานคร"

  company-b:
    name: "SiamTech Regional Office"
    description: "สาขาภาคเหนือ เชียงใหม่"
    
    # FIXED: Remove pool_size and max_overflow
    database:
      host: postgres-company-b
      port: 5432
      database: siamtech_company_b
      user: postgres
      password: password123
    
    knowledge_base:
      id: "dummy_kb_test_id"
      prefix: "company-b"
      bucket: "siamtech-kb-company-b"
      region: "ap-southeast-1"
      search_type: "SEMANTIC"
      max_results: 10
    
    api_keys:
      bedrock: "dummy_test_key_12345"
      bedrock_secret: "dummy_test_secret_67890"
    
    settings:
      max_tokens: 800
      temperature: 0.7
      allow_hybrid_search: true
      enable_postgres_agent: true
      enable_knowledge_base_agent: false
      enable_ollama_agent: true
      default_agent_type: "auto"
      response_language: "th"
    
    webhooks:
      n8n_endpoint: "http://n8n:5678/webhook/company-b-chat"
      health_check: "http://n8n:5678/webhook/company-b-health"
    
    contact_info:
      email: "regional@siamtech.co.th"
      phone: "053-123-456"
      address: "เชียงใหม่"

  company-c:
    name: "SiamTech International"
    description: "สำนักงานต่างประเทศ"
    
    # FIXED: Remove pool_size and max_overflow
    database:
      host: postgres-company-c
      port: 5432
      database: siamtech_company_c
      user: postgres
      password: password123
    
    knowledge_base:
      id: "dummy_kb_test_id"
      prefix: "company-c"
      bucket: "siamtech-kb-company-c"
      region: "ap-southeast-1"
      search_type: "SEMANTIC"
      max_results: 10
    
    api_keys:
      bedrock: "dummy_test_key_12345"
      bedrock_secret: "dummy_test_secret_67890"
    
    settings:
      max_tokens: 1200
      temperature: 0.6
      allow_hybrid_search: true
      enable_postgres_agent: true
      enable_knowledge_base_agent: false
      enable_ollama_agent: true
      default_agent_type: "auto"
      response_language: "en"
    
    webhooks:
      n8n_endpoint: "http://n8n:5678/webhook/company-c-chat"
      health_check: "http://n8n:5678/webhook/company-c-health"
    
    contact_info:
      email: "international@siamtech.co.th"
      phone: "+66-2-123-4567"
      address: "Bangkok, Thailand"

# Global settings
global_settings:
  fallback_agent: "ollama"
  retry_count: 3
  timeout_seconds: 30
  enable_debug_logging: true