services:


  n8n:
    image: n8nio/n8n:latest
    container_name: siamtech-n8n
    ports:
      - "5678:5678"
    environment:
      # n8n Configuration
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      
      # External Ollama Server
      - OLLAMA_BASE_URL=http://52.74.36.160:12434
      
      # Enhanced RAG Service URL
      - RAG_SERVICE_URL=http://hvac-ai-service:5000
      - ENHANCED_RAG_ENDPOINTS=true
      
      # Multi-tenant Database Configuration (for n8n nodes)
      - POSTGRES_HOST_COMPANY_A=postgres-company-a
      - POSTGRES_PORT_COMPANY_A=5432
      - POSTGRES_DB_COMPANY_A=siamtech_company_a
      - POSTGRES_USER_COMPANY_A=postgres
      - POSTGRES_PASSWORD_COMPANY_A=password123
      
      
      # Enhanced Models per Tenant
      - MODEL_COMPANY_A=llama3.1:8b

      
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - hvac_network
    restart: unless-stopped
    labels:
      - "com.siamtech.service=workflow-orchestrator"
      - "com.siamtech.integration=enhanced-rag"


# =============================================================================
# VOLUMES
# =============================================================================

volumes:
  n8n_data:
    driver: local
    
# =============================================================================
# NETWORK
# =============================================================================

networks:
  hvac_network:
    driver: bridge
    name: hvac_network